######################################################################################################################
# EXAMPLE DOCKERFILE
#
# REPLACE WITH YOURS



# Frontend Service Dockerfile
FROM nginx:alpine

COPY . .

# Expose the port the service will run on
EXPOSE 80

