services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - user-service
      - task-service

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    networks:
      - my-network
    environment:
      DATABASE_URL: postgres://youruser:yourpassword@db:5432/yourdb

  task-service:
    build: ./task-service
    ports:
      - "8082:8082"
    networks:
      - my-network
    depends_on:
      - user-service
      - db
    environment:
      DATABASE_URL: postgres://youruser:yourpassword@db:5432/yourdb


  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - my-network

  frontend:
    build: ./frontend-service
    ports:
      - "80:80"
    networks:
      - my-network

  # prometheus:
  #   image: prom/prometheus:latest
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - my-network

  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - my-network
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  my-network:
    driver: bridge

volumes:
  db-data:
