######################################################################################################################
# EXAMPLE DOCKERFILE
#
# REPLACE WITH YOURS



# Frontend Service Dockerfile
FROM alpine

COPY . .

EXPOSE 3000

